# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.141.4+1.21.11

# Additional Dependencies Properties
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.11&l=fabric
dep.modmenu=17.0.0
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.11&l=fabric
dep.yacl=3.8.2+1.21.11-fabric
# emotecraft, check https://modrinth.com/mod/emotecraft/versions?g=1.21.11&l=fabric
dep.emotecraft=3.2.0-b.build.151+1.21.11-fabric
# mossylib, check https://modrinth.com/mod/mossylib/versions?g=1.21.11&l=fabric
dep.mossylib=1.5.0+1.21.11+fabric
